name = "my-study-os-push"
main = "src/worker.js"
compatibility_date = "2026-04-26"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/send", "/schedule"]

[[kv_namespaces]]
binding = "ALARMS"
id = "dd321e04a43b455eaf4e42972f48d888"
